### PR TITLE
remove windows phone templates

### PR DESCRIPTION
**Pull request by emilioicai**

### CODE REVIEW

**Comment by secondsun** [comment]
+1

**Comment by pmdarrow** [comment]
There's a reference to Windows Phone in the README in this one too: 

```
README.md
7:Technologies: Windows Phone
```

Is this another repo where the template might not be valid without the Windows Phone project?

**Comment by emilioicai** [comment]
This one has also a Windows project so I think it should stay

**Comment by pmdarrow** [comment]
Ok. The reference in the README should probably be removed still though I think.

**Comment by emilioicai** [comment]
Done, I replaced Windows Phone with Windows

**Pull request merged**
